language: java
jdk:
  - oraclejdk8
  
services:
  - docker
  - docker-compose

before_script:
  - export MAVEN_OPTS="-Xmx2048m"

before_install:
  - git clone https://github.com/riveryang/dubbox.git
  - cd dubbox
  - ./build.sh
  - cd ..
  - rm -rf dubbox

install:
  - docker pull redis:alpine
  - docker run -d --name redis_6380 -p 6380:6379 redis:alpine
  - docker run -d --name redis_6381 -p 6381:6379 redis:alpine
  - docker-compose up -d

script:
  - ./build.sh

notifications:
  email: false
