language: java
jdk:
  - oraclejdk8
  
services:
  - docker
  - docker-compose

install:
  - docker pull redis:alpine
  - docker run -d --name redis_6380 -p 6380:6379 redis:alpine
  - docker run -d --name redis_6381 -p 6381:6379 redis:alpine
  - docker-compose up -d
  
before_script:
  - git clone https://github.com/riveryang/dubbox.git
  - cd dubbox
  - mvn clean install -Dmaven.test.skip=true
  - cd ..
  - rm -rf dubbox
  
notifications:
  email: false